### ISSUE TITLE
advice on implementing a GP that returns a unitary matrix

### ISSUE THREAD

**Issue by ctr** [geometric-kernels/GeometricKernels#153]
Hi,

I'm trying to implement a Gaussian Process approach to interpolating the computation of unitary (rotation) matrices in terms of two scalar parameters (e.g. A,B). I.e. for any (A,B) to get a unitary matrix.

A colleague recommended GeometricKernels to us.

But we are struggling to understand whether we can use it to make a Gaussian Process that returns a unitary matrix value as opposed to a Gaussian Process that gives a scalar value as a function of coordinates that represent a unitary matrix.

We were hoping not to just use a Gaussian Process to represent each element of the matrix because then it may well not be a unitary matrix which would spoil the use-case by violating the physics symmetry.

Is this type of problem that GeometricKernels may be able to help us with? Or if not, do you have any recommendations for an alternative approach?

I'd be happy to speak and explain more if it's easier for you than emails.

Many thanks, Chris.

**Comment by vabor112** [comment]
Dear @ctr,

Unfortunately, GeometricKernels can only help with inputs on non-Euclidean spaces, not outputs.

I'm not sure if you actually want unitary matrices or orthogonal matrices, because it is the latter that typically represent rotations in the most usual sense of this word. If you are indeed interested in unitary matrices, you could use the parameterization $U = e^{i A}$ where $A$ is a Hermitian matrix, something easy to parameterize. If you are interested in orthogonal matrices, you can represent them as $O = e^A$ where A is a skew-symmetric matrix, also easy to parameterize (this actually only covers orthogonal matrices with determinant 1, which should be okay because determinant -1 allows for reflections, not only rotations). With these representations, you can regress the individual entries of the upper triangular part of $A$, which determines the whole $A$, which you can then transform into a unitary/orthogonal matrix.

One general approach for Euclidean-to-manifold Gaussian process can be found here: https://openaccess.thecvf.com/content_cvpr_2018/papers/Mallasto_Wrapped_Gaussian_Process_CVPR_2018_paper.pdf. I don't know much about its implementations though.

Hope this helps!
